; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f091rc]
platform = ststm32
board = nucleo_f091rc
framework = cmsis
upload_protocol = stlink
build_flags =
    -DSTM32F091xC
    -I $PROJECT_DIR/src
    -I $PROJECT_DIR/lib
    -I $PROJECT_DIR/include
    -I $PROJECT_DIR/.pio/libdeps/nucleo_f091rc/framework-cmsis-stm32f0/Include  ; Path to CMSIS STM32F0 header files
    -I $PROJECT_DIR/.pio/libdeps/nucleo_f091rc/framework-cmsis/Include          ; Path to CMSIS core header files
    -I $PROJECT_DIR/.pio/libdeps/nucleo_f091rc/framework-cmsis-stm32f0/Source/Templates ; Source path
upload_command = openocd -f openocd.cfg -c "program .pio/build/nucleo_f091rc/firmware.elf verify reset exit"
debug_server = 
    ${platformio.packages_dir}/tool-openocd/bin/openocd
    -f
    openocd.cfg
debug_init_break = tbreak main